version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Rez@ul123
      MYSQL_DATABASE: studentdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: ./student-backend
    container_name: backend
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/studentdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Rez@ul123
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  frontend:
    build:
      context: .
      dockerfile: ./student-frontend
    container_name: frontend
    restart: always
    ports:
      - "80:80"

volumes:
  mysql_data:


