apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular
spec:
  selector:
    matchLabels:
      app: angular
  replicas: 1
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
        - name: angular
          image: imrezaulkrm/angular:5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angular
  labels:
    app: angular
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: angular
  type: ClusterIP

